//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.488
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeosSdiConfiguration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class SettingsNeosSdi : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsNeosSdi defaultInstance = ((SettingsNeosSdi)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsNeosSdi())));
        
        public static SettingsNeosSdi Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::NeosSdiConfiguration.ConfigurationSettings Configuration {
            get {
                return ((global::NeosSdiConfiguration.ConfigurationSettings)(this["Configuration"]));
            }
            set {
                this["Configuration"] = value;
            }
        }
    }
}
